
extern char*						ex_cpu_models[];
extern char*						ex_cpu_wcachesiz[];
extern BOOL							code_freerun,code_showallsteps;
extern BOOL							exec_ROR_o;
extern int							exec_RC_carry;
extern int							code_showstepcnt;
extern int							code_cpuspeed;
extern int							exec_show,exec_step;
extern int							cpu_revision;
extern BOOL							ExecuteBusy;
extern BOOL							edb66,edb67;
extern int							exec_imm1;
extern int							exec_bit;
extern BOOL							exec_buslock;
extern BOOL							pf_8088;
extern int							exec_buslockcnt;
extern DWORD						rep_loopaddr_cs,rep_loopaddr_ip;
extern BOOL							REPLoop;
extern BOOL							REPZflag;
extern DWORD                        oireg_eip;
extern BOOL                         segov;
extern int                          procREP;
extern int                          exec_cycle;
extern DWORD						ireg_eip;
extern DWORD						ireg_eax;
extern DWORD						ireg_ebx;
extern DWORD						ireg_ecx;
extern DWORD						ireg_edx;
extern DWORD						ireg_esi;
extern DWORD						ireg_edi;
extern DWORD						ireg_esp;
extern DWORD						ireg_ebp;
extern DWORD						ireg_cs;
extern DWORD						ireg_ds;
extern DWORD						ireg_es;
extern DWORD						ireg_fs;
extern DWORD						ireg_gs;
extern DWORD						ireg_ss;
extern DWORD						ireg_cr0;
extern DWORD						ireg_flags;
extern LONG							ireg_idtr;
extern LONG							ireg_gdtr;
extern WORD							ireg_ldtr;
extern DWORD*						ireg_dataseg;
extern int							ireg_datasegreset;
extern BYTE							fpu_87_state[94];
extern long double					fpu_87_stack[8];
extern DWORD*						regptr_dec32[];
extern WORD*						regptr_dec[];
extern BYTE*						regptr_decbyte[];
extern WORD*						regptr_seg[];
extern int							interrupt_signal;
extern int							nmi_interrupt_signal;
extern int							opcode_denies_intproc;

void InterruptCPU(int n);
DWORD Execute();
void ConfigureCPU();
void ExecutioneerReset();
void ExecutionStep();
void ExecutionShow();
void StepExecute();
void InitExecutioneer();
void CloseExecutioneer();
void ExecutioneerPowerOn();
void ExecutioneerPowerOff();
int ExecutioneerIsPowered();
